version: "3.0"

services: 
  frontstore:
    build: 
      context: ./frontstore/docker/dev
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes: 
      - ./frontstore:/usr/src/app
      - frontstore-node-modules:/usr/src/app/node_modules
    # links:
    # environment:

  core-api:
    build:
      context: ./core-api/docker/dev
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes: 
      - ./core-api:/usr/src/app
      - core-api-node-modules:/usr/src/app/node_modules
    links: 
      - pg
    environment:
      - DB_HOST=pg
      - DB_USER=core_database
      - DB_PASSWORD=pass
      - DB_NAME=core_database
  
  pg:
    image: postgres:9.6.15
    volumes:
      - ./postgres-data:/docker-entrypoint-initdb.d
    ports: 
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - PGPASSWORD=pass
    command: postgres -c max_connections=200
      
volumes: 
  core-api-node-modules:
  frontstore-node-modules:
  
networks:
  default:
    ipam:
      driver: default